<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_kultuer-veranstaltung',
		'title' => 'KULTÜR Veranstaltung',
		'fields' => array (
			array (
				'key' => 'field_585d39d549ea8',
				'label' => 'Ort',
				'name' => 'place',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_585d39e949ea9',
				'label' => 'Datum',
				'name' => 'date',
				'type' => 'date_picker',
				'required' => 1,
				'date_format' => 'yymmdd',
				'display_format' => 'dd.mm.yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_585d3a0949eaa',
				'label' => 'Uhrzeit',
				'name' => 'time',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => 'Z.B. 10:00',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_585d3a2749eab',
				'label' => 'Link zum Veranstalter',
				'name' => 'link',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_585d3c8e3a13e',
				'label' => 'Keine Buchung nötig',
				'name' => 'no_booking',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_585d3a3949eac',
				'label' => 'Anzahl Karten',
				'name' => 'num_tickets',
				'type' => 'number',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585d3c8e3a13e',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_585d3a8d49ead',
				'label' => 'Buchbar bis ...',
				'name' => 'order_until',
				'type' => 'date_picker',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585d3c8e3a13e',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'date_format' => 'yymmdd',
				'display_format' => 'dd.mm.yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_585d3add49eae',
				'label' => 'Buchbar für Gruppen bis ...',
				'name' => 'order_until_groups',
				'type' => 'date_picker',
				'instructions' => 'Muss nicht ausgefüllt werden, wenn die Buchungslimits gleich sind.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_585d3c8e3a13e',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'date_format' => 'yymmdd',
				'display_format' => 'dd.mm.yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_58b83c59119f0',
				'label' => 'Schon vergebene Tickets',
				'name' => 'num_tickets_assigned',
				'type' => 'number',
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'kultuer_event',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
?>
